/**
 * BOA Pricing Page Renderer
 *
 * Loads pre-computed pricing data from data/pricing-data.json
 * (generated by scripts/generate-pricing.mjs) and renders it.
 *
 * No pricing computation happens here — all numbers come from
 * the generator, which fetches live rates from the AWS Pricing API.
 */

(async function () {
  const resp = await fetch('data/pricing-data.json');
  if (!resp.ok) {
    document.getElementById('comparison-body').innerHTML =
      '<tr><td colspan="6">Failed to load pricing data. Run: node website/scripts/generate-pricing.mjs</td></tr>';
    return;
  }
  const data = await resp.json();

  const { appProfiles, sizeTiers, scenarios } = data;

  // Expose for debugging
  window.BOAPricingData = data;

  // --- Formatting helpers ---

  function formatMoney(val) {
    if (val === 0) return '$0';
    if (val < 0.01) return '<$0.01';
    if (val >= 100) return `$${val.toLocaleString('en-US', { maximumFractionDigits: 0 })}`;
    return `$${val.toFixed(2)}`;
  }

  function formatNumber(n) {
    if (n >= 1000000000) return `${(n / 1000000000).toFixed(1)}B`;
    if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
    if (n >= 1000) return `${(n / 1000).toFixed(0)}K`;
    return n.toString();
  }

  // --- DOM refs ---

  const appSelect = document.getElementById('app-select');
  const comparisonBody = document.getElementById('comparison-body');
  const breakdownGrid = document.getElementById('breakdown-grid');
  const generatedDate = document.getElementById('generated-date');

  if (generatedDate) {
    generatedDate.textContent = data.generatedAt.slice(0, 10);
  }

  // --- Render ---

  function render() {
    const profileKey = appSelect.value;
    const results = scenarios[profileKey];
    if (!results) return;

    // Comparison table
    comparisonBody.innerHTML = results.map(r => {
      const size = sizeTiers[r.workload.sizeKey];
      const boaClass = r.boa.total === 0 ? 'price-free' : 'price-boa';
      const boaLabel = r.boa.total === 0 ? '$0 (free tier)' : formatMoney(r.boa.total);
      const supaLabel = r.supa.total === 0 ? '$0 (free tier)' : formatMoney(r.supa.total);

      let savingsHTML = '';
      if (r.supa.total === 0 && r.boa.total === 0) {
        savingsHTML = '<span style="color:var(--green-dark)">Both free</span>';
      } else if (r.boa.total === 0 && r.supa.total > 0) {
        savingsHTML = `<span style="color:var(--green-dark)">Save ${formatMoney(r.supa.total)}/mo</span>`;
      } else if (r.boa.total < r.supa.total) {
        const pct = Math.round(((r.supa.total - r.boa.total) / r.supa.total) * 100);
        savingsHTML = `<span style="color:var(--green-dark)">${pct}% less (save ${formatMoney(r.supa.total - r.boa.total)})</span>`;
      } else if (r.boa.total > r.supa.total) {
        const pct = Math.round(((r.boa.total - r.supa.total) / r.supa.total) * 100);
        savingsHTML = `<span style="color:var(--gray-500)">Supabase ${pct}% less</span>`;
      } else {
        savingsHTML = '<span style="color:var(--gray-500)">Same</span>';
      }

      return `<tr>
        <td>
          <div class="tier-name">${size.name}</div>
          <div class="tier-desc">${size.desc}</div>
        </td>
        <td>${formatNumber(size.users)}</td>
        <td><span class="price-val ${boaClass}">${boaLabel}</span></td>
        <td><span class="price-val price-competitor">${supaLabel}</span></td>
        <td>${savingsHTML}</td>
        <td style="color:var(--gray-500); font-size:0.85rem">${r.supa.plan} + ${r.supa.tier}</td>
      </tr>`;
    }).join('');

    // Breakdown cards
    breakdownGrid.innerHTML = results.map(r => {
      const size = sizeTiers[r.workload.sizeKey];
      const total = r.boa.total;
      const totalClass = total === 0 ? 'free' : 'paid';
      const totalLabel = total === 0 ? '$0/mo' : `${formatMoney(total)}/mo`;

      const lines = [
        { service: 'Aurora DSQL', cost: r.boa.dsql },
        { service: 'Cognito', cost: r.boa.cognito },
        { service: 'Lambda', cost: r.boa.lambda },
        { service: 'API Gateway', cost: r.boa.apiGateway },
        { service: 'S3', cost: r.boa.s3 },
      ];

      const linesHTML = lines.map(l => {
        const costClass = l.cost === 0 ? 'free-tier' : '';
        const costLabel = l.cost === 0 ? '$0 (free)' : formatMoney(l.cost);
        return `<div class="line-item">
          <span class="service">${l.service}</span>
          <span class="cost ${costClass}">${costLabel}</span>
        </div>`;
      }).join('');

      return `<div class="breakdown-card">
        <h3>${size.name} — ${formatNumber(size.users)} users</h3>
        <div class="total-price ${totalClass}">${totalLabel}</div>
        ${linesHTML}
        <div class="line-item" style="margin-top:0.5rem; border-top: 2px solid var(--gray-200); padding-top:0.5rem;">
          <span class="service" style="font-weight:600;">vs Supabase</span>
          <span class="cost">${formatMoney(r.supa.total)}/mo</span>
        </div>
      </div>`;
    }).join('');
  }

  appSelect.addEventListener('change', render);
  render();
})();
